// 最终提示词生成规则 - 用于生成最终高质量系统提示词的内置规则
// 重新导出各个独立的提示词文件

import { THINKING_POINTS_EXTRACTION_PROMPT, THINKING_POINTS_SYSTEM_MESSAGE } from './thinkingPointsExtraction'
import { SYSTEM_PROMPT_GENERATION_PROMPT, SYSTEM_PROMPT_SYSTEM_MESSAGE } from './systemPromptGeneration'
import { OPTIMIZATION_ADVICE_PROMPT, OPTIMIZATION_ADVICE_SYSTEM_MESSAGE } from './optimizationAdvice'
import { OPTIMIZATION_APPLICATION_PROMPT, OPTIMIZATION_APPLICATION_SYSTEM_MESSAGE } from './optimizationApplication'

export const FINAL_PROMPT_GENERATION_RULES = {
  // 系统提示词关键指令提取规则
  THINKING_POINTS_EXTRACTION: THINKING_POINTS_EXTRACTION_PROMPT,

  // 系统提示词生成规则
  SYSTEM_PROMPT_GENERATION: SYSTEM_PROMPT_GENERATION_PROMPT,

  // 优化建议生成规则
  OPTIMIZATION_ADVICE_GENERATION: OPTIMIZATION_ADVICE_PROMPT,

  // 优化应用规则
  OPTIMIZATION_APPLICATION: OPTIMIZATION_APPLICATION_PROMPT
}

// 系统消息配置
export const FINAL_PROMPT_SYSTEM_MESSAGES = {
  THINKING_POINTS_SYSTEM: THINKING_POINTS_SYSTEM_MESSAGE,
  SYSTEM_PROMPT_SYSTEM: SYSTEM_PROMPT_SYSTEM_MESSAGE,
  OPTIMIZATION_ADVICE_SYSTEM: OPTIMIZATION_ADVICE_SYSTEM_MESSAGE,
  OPTIMIZATION_APPLICATION_SYSTEM: OPTIMIZATION_APPLICATION_SYSTEM_MESSAGE
}